### PR TITLE
Main Page Buttons Assets

### PR DESCRIPTION
**Pull request by IqbalBan**

### CODE REVIEW

**Comment by SachJay** [comment]
Pictures have a white background, i guess its fine for now but if this becomes a problem were flaming you.

**Review by SachJay — APPROVED** [review]
Make sure to have a desc for each PR just so people know what this is for

**Comment by SachJay** [comment]
LOL Ignore those last 2 commits 👀 hmmm luke inted again

**Comment by SachJay** [comment]
When you merge it to master make sure the merge button is set to `Squash and merge` by default its not set to that.
image

**Review by AndCrit — APPROVED** [review]
Can't see the images and I hope they don't look too bad

**Pull request merged**
